### ISSUE TITLE
Why so many options

### ISSUE THREAD

**Issue by klaernie** [hazymat/openhab-chrome#3]
reading the code I noticed that you hardcoded the path structure in [popup.js#L3](https://github.com/hazymat/openhab-chrome/blob/7c526bc2aac005146033f7b74232e90841a7421c/popup.js#L3). Why not allow the user to specify the full URL? This should solve the problem that `https://` cannot be specified.

And once HTTPS is working one might try if SSO via SSL Client Certificate Authentication works, this is support by the Android App, and might work as you don't need to store any credentials as well.

**Comment by lucianopeixoto** [comment]
According to the description on chrome store page (https://chrome.google.com/webstore/detail/mini-openhab-controller/lphilmckagfijcikbfoibgekcoodaobd?utm_source=chrome-app-launcher-info-dialog) it's not a simple task to make HTTPS work properly in a chrome extension:

> ** SADLY NO SUPPORT FOR HTTPS or AUTHENTICATION **
>
> I know - it's rubbish :(
> 
> But unless I break Google's T&Cs and store credentials in an unencrypted data store, or unless OpenHAB implements OAuth2, that's what we are stuck with.
> 
> Chrome isn't able to use the same authenticated session as in the browser. If anyone has any other bright ideas about the above, I've published the source here: https://github.com/hazymat/openhab-chrome

Maybe someone could help with that feature.
